exclude:
- /_setup_support.py
- /conda.recipe/.*
- /conftest.py
- /docker-tools/.*
- /examples/.*
- /scripts/.*
- /setup.py
- /sphinx/.*
- /versioneer.py
component_depth: 1
languages:
- javascript
- python
- script
- typescript
